### ISSUE TITLE
Publishing to crates.io?

### ISSUE THREAD

**Issue by sfackler** [sbstp/tokio-dns#7]
Is anything blocking publishing this to crates.io?

**Comment by sbstp** [comment]
I asked Carl if I could use the name `tokio-dns` name a while back and he said that he'd rather keep the `tokio-` namespace for official projects. I guess I could publish it under `tokio-dns-unofficial` or something.

**Comment by sbstp** [comment]
There you go: https://crates.io/crates/tokio-dns-unofficial

The docs should appear eventually...

**Comment by sfackler** [comment]
Thanks!

**Comment by sbstp** [comment]
Going to close this for now, let me know if you have other issues.
